import { t, setUiLanguage } from './i18n';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { listen } from '@tauri-apps/api/event';
import { CalendarDays, FileText, Home, Mic, MoreHorizontal, PanelLeftClose, PanelLeftOpen, Search, Settings as SettingsIcon, Square, Volume2, X } from 'lucide-react';
import { api } from './api';
import { MeetingRow } from './ui';
import { CalendarPage, DetailsPage, MeetingsPage, SearchPage, SettingsPage } from './pages';
import { titleOf, type Meeting, type Settings, type Snapshot } from './types';
import './App.css';

type Page = 'home' | 'meetings' | 'search' | 'calendar' | 'settings' | 'details';
const fallback: Snapshot = { meetings: [], settings: { theme: 'system', language: 'en', launchAtLogin: false, minimizeToTray: true, microphoneId: '', systemAudioId: '', recordingPath: '', transcriptionModel: 'gpt-4o-mini-transcribe', summaryModel: 'gpt-4o-mini', summaryLanguage: 'Russian', shortcut: 'Ctrl+Shift+R' }, keyConnected: false, recordingStartedAt: null, microphones: [], outputs: [] };
const nav = [{ id: 'home', label: 'Home', icon: Home }, { id: 'meetings', label: 'Meetings', icon: FileText }, { id: 'search', label: 'Search', icon: Search }, { id: 'calendar', label: 'Calendar', icon: CalendarDays }, { id: 'settings', label: 'Settings', icon: SettingsIcon }] as const;
const errorText = (error: unknown) => typeof error === 'string' ? error : error instanceof Error ? error.message : 'Something went wrong.';
export default function App() {
  const [snapshot, setSnapshot] = useState<Snapshot>(fallback); const [page, setPage] = useState<Page>('home');
  const [selectedId, setSelectedId] = useState<string | null>(null); const [tab, setTab] = useState<'overview' | 'transcript'>('overview');
  const [collapsed, setCollapsed] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [deleteMeeting, setDeleteMeeting] = useState<Meeting | null>(null); const [renameMeeting, setRenameMeeting] = useState<Meeting | null>(null); const [titleDraft, setTitleDraft] = useState('');
  const [now, setNow] = useState(Date.now());
  const refresh = useCallback(async () => { try { setSnapshot(await api.snapshot()); } catch (e) { setError(errorText(e)); } }, []);
  useEffect(() => { refresh(); const timer = window.setInterval(() => setNow(Date.now()), 1000); let listeners: (() => void)[] = []; Promise.all(['meeting-updated', 'recording-changed', 'settings-updated'].map(event => listen(event, refresh))).then(items => listeners = items); return () => { clearInterval(timer); listeners.forEach(fn => fn()); }; }, [refresh]);
  useEffect(() => { const setTheme = () => { document.documentElement.dataset.theme = snapshot.settings.theme === 'system' ? (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : snapshot.settings.theme; }; setTheme(); const media = matchMedia('(prefers-color-scheme: dark)'); media.addEventListener('change', setTheme); return () => media.removeEventListener('change', setTheme); }, [snapshot.settings.theme]);
  setUiLanguage(snapshot.settings.language);
  const meetings = useMemo(() => [...snapshot.meetings].sort((a,b) => b.startedAt.localeCompare(a.startedAt)), [snapshot.meetings]);
  const selected = meetings.find(m => m.id === selectedId);
  const openMeeting = (id: string) => { setSelectedId(id); setTab('overview'); setPage('details'); };
  const start = async () => { setBusy(true); setError(''); try { await api.start(); await refresh(); setPage('home'); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } };
  const stop = async () => { setBusy(true); setError(''); try { const meeting = await api.stop(); await refresh(); openMeeting(meeting.id); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } };
  const updateSettings = async (changes: Partial<Settings>) => { const settings = { ...snapshot.settings, ...changes }; setSnapshot(current => ({ ...current, settings })); try { await api.saveSettings(settings); await refresh(); } catch (e) { setError(errorText(e)); await refresh(); } };
  const actions = (meeting: Meeting) => ({ onOpen: () => openMeeting(meeting.id), onRename: () => { setRenameMeeting(meeting); setTitleDraft(titleOf(meeting)); }, onDelete: () => setDeleteMeeting(meeting), onAudio: () => api.openAudio(meeting.id).catch(e => setError(errorText(e))) });
  const saveTitle = async () => { if (!renameMeeting || !titleDraft.trim()) return; try { await api.rename(renameMeeting.id, titleDraft.trim()); setRenameMeeting(null); await refresh(); } catch (e) { setError(errorText(e)); } };
  const remove = async () => { if (!deleteMeeting) return; try { await api.remove(deleteMeeting.id); if (selectedId === deleteMeeting.id) setPage('meetings'); setDeleteMeeting(null); await refresh(); } catch (e) { setError(errorText(e)); } };
  const seconds = snapshot.recordingStartedAt ? Math.max(0, Math.floor((now - new Date(snapshot.recordingStartedAt).getTime()) / 1000)) : 0;
  const clock = `${String(Math.floor(seconds / 3600)).padStart(2,'0')}:${String(Math.floor(seconds / 60) % 60).padStart(2,'0')}:${String(seconds % 60).padStart(2,'0')}`;
  return <div className="shell"><aside className={`sidebar ${collapsed ? 'collapsed' : ''}`}><div className="window-dots"><i/><i/><i/></div><div className="brand"><strong>Meeting Notes</strong><span>{t('Local meeting memory')}</span></div><nav>{nav.map(item => <button key={item.id} className={`nav-item ${page === item.id || page === 'details' && item.id === 'meetings' ? 'active' : ''}`} title={t(item.label)} onClick={() => setPage(item.id)}><item.icon size={22} strokeWidth={1.8}/><span>{t(item.label)}</span></button>)}</nav></aside><div className="main-area"><div className="chrome-actions"><button className="icon-button" title={t('Toggle sidebar')} onClick={() => setCollapsed(!collapsed)}>{collapsed ? <PanelLeftOpen size={19}/> : <PanelLeftClose size={19}/>}</button><button className="icon-button" title={t('Settings')} onClick={() => setPage('settings')}><MoreHorizontal size={20}/></button></div>{error && <div className="error-banner">{error}<button onClick={() => setError('')} aria-label={t('Dismiss')}><X size={17}/></button></div>}
    {page === 'home' && <main className="page home-page">{snapshot.recordingStartedAt ? <section className="home-hero"><div className="recording-label"><i/>{t('Recording')}</div><h1 className="timer">{clock}</h1><div className="device-status"><span><Mic size={19}/>{t('Microphone')}</span><span><Volume2 size={19}/>{t('System audio')}</span></div><button className="primary stop-button" disabled={busy} onClick={stop}><Square size={15} fill="currentColor"/>{t('Stop recording')}</button></section> : <section className="home-hero"><h1>{t('Ready to record')}</h1><p>{t('Record your meetings, transcribe them, and create useful notes')}<br/>{t('all locally on your device.')}</p><button className="primary start-button" disabled={busy} onClick={start}>{t('Start recording')}</button><div className="device-status"><span><Mic size={19}/><i className={snapshot.microphones.length ? 'ok-dot' : 'bad-dot'}/>{snapshot.microphones.length ? t('Microphone connected') : t('Microphone unavailable')}</span><span><Volume2 size={19}/><i className={snapshot.outputs.length ? 'ok-dot' : 'bad-dot'}/>{snapshot.outputs.length ? t('System audio ready') : t('System audio unavailable')}</span></div></section>}<section className="recent"><div className="section-header"><h2>{t('Recent meetings')}</h2><button onClick={() => setPage('meetings')}>{t('View all')} ›</button></div>{meetings.slice(0,5).map(m => <MeetingRow key={m.id} meeting={m} compact {...actions(m)}/>)}{meetings.length === 0 && <p className="empty">{t('Your recordings will appear here.')}</p>}</section></main>}
    {page === 'meetings' && <MeetingsPage meetings={meetings} actions={actions}/>}
    {page === 'search' && <SearchPage onOpen={openMeeting} onError={setError}/>}
    {page === 'calendar' && <CalendarPage meetings={meetings} onOpen={openMeeting}/>}
    {page === 'settings' && <SettingsPage snapshot={snapshot} update={updateSettings} refresh={refresh} onError={setError}/>}
    {page === 'details' && selected && <DetailsPage meeting={selected} tab={tab} setTab={setTab} back={() => setPage('meetings')} rename={actions(selected).onRename} retry={async () => { try { await api.retry(selected.id); await refresh(); } catch (e) { setError(errorText(e)); } }} toggle={async (id, completed) => { try { await api.toggleAction(id, completed); await refresh(); } catch (e) { setError(errorText(e)); } }} openAudio={actions(selected).onAudio}/>}
  </div>{deleteMeeting && <div className="modal-backdrop"><div className="modal"><h2>{t('Delete meeting?')}</h2><p>{t('This removes the transcript, notes, and local recording for')} «{titleOf(deleteMeeting)}».</p><div className="modal-actions"><button className="secondary" onClick={() => setDeleteMeeting(null)}>{t('Cancel')}</button><button className="danger" onClick={remove}>{t('Delete')}</button></div></div></div>}{renameMeeting && <div className="modal-backdrop"><div className="modal"><h2>{t('Rename meeting')}</h2><input autoFocus value={titleDraft} onChange={e => setTitleDraft(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') saveTitle(); if (e.key === 'Escape') setRenameMeeting(null); }}/><div className="modal-actions"><button className="secondary" onClick={() => setRenameMeeting(null)}>{t('Cancel')}</button><button className="primary" onClick={saveTitle}>{t('Save')}</button></div></div></div>}</div>;
}
